version: '3.7'
services:
  mysql:
    image: mysql
    networks:
      backend:
        aliases:
          - db
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./db:/var/lib/mysql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=$$3cureUS
      - MYSQL_DATABASE=db

  models:
    image: tp33/django
    volumes:
      - ./app/deploy_project:/app
    ports:
      - "8001:8000"
    depends_on:
      - mysql
    networks:
      - backend
    command: >
      /bin/bash -c "
        while ! nc -z mysql;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      sleep 10 && python manage.py makemigrations
      && python manage.py migrate && python manage.py flush --no-input -v 0
      && python manage.py loaddata db.json
      && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/deploy_project/wsgi.py"

networks:
  backend:
    driver: bridge
