version: '2.1'
services:
  mysql:
    image: mysql
    networks:
      backend:
        aliases:
          - db
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./db:/var/lib/mysql
    command: --init-file /data/application/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=$$3cureUS
      - MYSQL_DATABASE=db

  models:
    image: tp33/django
    volumes:
      - ./app/deploy_project:/app
    ports:
      - "80:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    command: bash start-microservices.sh

networks:
  backend:
    driver: bridge
