version: '3.7'
services:
  mysql:
    image: mysql
    networks:
      backend:
        aliases:
          - db
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./db:/var/lib/mysql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=$$3cureUS
      - MYSQL_DATABASE=db
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 20s
        timeout: 10s

  models:
    image: tp33/django
    volumes:
      - ./app/deploy_project:/app
    ports:
      - "8001:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    command: bash start-microservices.sh

networks:
  backend:
    driver: bridge
