# Generated by Django 2.2.4 on 2019-09-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Government_Citizens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.Government')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.Enterprise')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.Enterprise')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.Person')),
            ],
        ),
    ]
