# Generated by Django 2.2.4 on 2019-09-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enterprise_Employee',
            new_name='Enterprise_Customers',
        ),
        migrations.RenameModel(
            old_name='Enterprise_Customer',
            new_name='Enterprise_Employees',
        ),
    ]
