# Generated by Django 2.2.4 on 2019-10-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0004_auto_20191009_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='validFrom',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='validTo',
            new_name='valid_to',
        ),
    ]
