# Generated by Django 2.2.4 on 2019-10-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0005_auto_20191009_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='required',
        ),
    ]
