# Generated by Django 2.2.4 on 2019-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0006_remove_document_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='icon',
            field=models.URLField(null='true'),
            preserve_default='true',
        ),
    ]
